config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :categories

  
  devise_for :users, path: 'users', controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}

devise_for :admins, path: 'admins', controllers: {
  sessions: 'admins/sessions',
  registrations: 'admins/registrations'
}

devise_scope :user do
  authenticated :user do
    namespace :users do
      get 'buyersdash/buyerdash', as: :authenticated_root
    end
  end
end

devise_scope :admin do
  authenticated :admin do
    namespace :admins do
      get 'dashboard/index', as: :authenticated_root
      
    end
  end
end

get 'jobs/index'
 get 'users/sellersdash/sellerdash'
#get 'users/sellersdash/sellersdash', action: :sellerdash, controller: 'users'
#get 'users/sellersdash/sellerdash', to: 'users#sellersdash#sellerdash'

root to: 'pages#landing'
#get "/get_subcategories" => "jobs#get_subcategories"
#get 'jobs/partial/subcategories'
#get 'jobs/partial/subcategories' => 'jobs#get_subcategories'
#get "/get_subcategories" => "jobs#get_subcategories"
#get "/get_subsubcategories" => "jobs#get_subsubcategories"

#get"/jobs", to: "jobs#category"
 

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :jobs
    belongs_to :parent_category, foreign_key: :parent_id, class_name: 'Category'
    has_many :subcategories, foreign_key: :parent_id, class_name: 'Category'
    has_many :subsubcategories, foreign_key: :parent_id, class_name: 'Category'

end

app/models/job.rb
class Job < ApplicationRecord

 validates :title,:category_id, :description, presence: true
 validates :category, :presence => true

 belongs_to :user
 belongs_to :category , -> { order("name") }

 
 
 
 


 
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
         has_many :jobs, dependent: :destroy
         enum role: { buyer: 0, seller: 1 } 

      
 end

 

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
  def index
  end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_resource, only: :destroy

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :role) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :role) }
        end
      
end

app/controllers/concerns/accessible.rb
module Accessible
    extend ActiveSupport::Concern
    included do
      before_action :check_resource
    end
  
    protected
  
    def check_resource
      if admin_signed_in?
        flash.clear
        redirect_to(admins_authenticated_root_path) and return
      elsif user_signed_in?
        flash.clear
        redirect_to(users_authenticated_root_path) and return
      end
    end


    def after_sign_up_path_for(resource)
      if admin_signed_in?
        flash.alert = "redirected to admin dash ."
        admins_authenticated_root_path
            elsif user_signed_in?
          flash.alert = "redirected to user dash ."
      users_authenticated_root_path
            else
              root_path
     end
    end









  end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_categories

 
  
  def index
    @jobs = Job.all
    @category = Category.all

   
  end
 

 
 
  def new
    #@category = Category.new
    @categories = Category.where(parent_id: nil)  
    @subcategory = @subcategory&.category || []
    @subcategories = @subcategories&.subcategories || []
    @subsubcategories = @subsubcategories&.subsubcategories || []
 
    @job = Job.new
  

   
  end


  def create
  
  @job = Job.new(job_params.merge({ user: current_user }))
    if @job.save
  format.html { redirect_to root_path, notice: "Job was successfully created." }
    else
    render :new, status: :unprocessable_entity
    
  end
end

private
def job_params
  params.require(:job).permit(:title, :description,:category_id).merge(user: current_user)

end

 



 def set_categories
  @category = Category.find_by(id: params[:category].presence)
  @categories = Category.find_by(id: params[:category].presence)
  @subcategories = Category.find_by(id: params[:category].presence)
  @subsubcategories = Category.find_by(id: params[:subcategories].presence)

 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: :landing
 
  
  
  
  
  def landing
    
  end

 
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_resource, only: :destroy

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users/buyersdash_helper.rb
module Users::BuyersdashHelper
end

app/helpers/users/sellersdash_helper.rb
module Users::SellersdashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

  </head>

  <body>
 <div class="container">

 
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">JobBoard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Home", root_path, class: "nav-link " %>
        </li>

    <li class="nav-item">
    <%= link_to "Jobs", jobs_path, class: "nav-link " %>
      </li>
<% if current_page?(users_authenticated_root_path) %>
 <li class="nav-item">

 <%= link_to  "Switch to Selling", users_sellersdash_sellerdash_path	 , class: "nav-link " %>
 </li>
<% end %>

<% if current_page?(users_sellersdash_sellerdash_path	 ) %>
 <li class="nav-item">
 <%= link_to "Switch to Buying", users_authenticated_root_path, class: "nav-link " %>
 </li>
<% end %>





        
         <li class="nav-item">
           <%= link_to "admin sign in", admin_session_path, class: "nav-link " %>
           

        </li>
        
      </ul>


 <ul class="navbar-nav   mb-2 mb-lg-0">

 <% if user_signed_in? %>

 <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle"id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false href="#"> Welcome back <%= current_user.email if user_signed_in? %> </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
     <li><a class="dropdown-item" <%= link_to "Post a Job Request", new_job_path  %> </a></li>
       <li><a class="dropdown-item" <%= link_to "My Dashboard", users_authenticated_root_path  %> </a></li>

    <li><a class="dropdown-item" <%= link_to "User Sign out", destroy_user_session_path, :method => :delete %> </a></li>
    </ul>
  </li>
  
  
 <% elsif !admin_signed_in? %>



 <li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false href="#"> Hello </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
  
   <li><a class="dropdown-item"  <%= link_to "user Sign up",  new_user_registration_path %> </a></li>   
      <li><a class="dropdown-item"  <%= link_to "user Signin",  new_user_session_path %> </a></li>   

  </ul>
 </li> 

 <% end %>


 <% if admin_signed_in? %>

<li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle"id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false href="#"> Welcome back <%= current_admin.email if admin_signed_in? %> </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
  
       <li><a class="dropdown-item" <%= link_to "My Dashboard", admins_authenticated_root_path  %> </a></li>
    <li><a class="dropdown-item" <%= link_to "Sign Out as Admin", destroy_admin_session_path, :method => :delete %> </a></li>
  </ul> 
  
  </li>


   <% end %>
 
   </ul>
    </div>
  </div>
</nav>

 </div>
   <div class="container noticex">

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
</div>
    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<div class="container">


<h1>Pages#landing</h1>
<p>Find me in app/views/pages/landing.html.erb</p>




 

</div>